//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class user
    {
        public int user_Id { get; set; }
     
        [Required]
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
          
        [Required]
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
    }
}
